
development:
  adapter: postgresql
  schema_search_path: public
  host: "<%= ENV['local_database_host'] %>"
  port: "<%= ENV['local_database_port'] %>"
  database: "dev_number_one_development"
  username: "<%= ENV['local_database_user'] %>"
  password: "<%= ENV['local_database_pass'] %>"

test:
  adapter: postgresql
  schema_search_path: public
  host: "<%= ENV['teste_database_host'] %>"
  port: "<%= ENV['teste_database_port'] %>"
  database: "dev_number_one_test"
  username: "<%= ENV['teste_database_user'] %>"
  password: "<%= ENV['teste_database_pass'] %>"